let products = [
    {sku:'1', name:'Camiseta negra', price: 30, image: './images/shirt.png', description: 'Camiseta negra de hombre en tela fria', category: 'Camisetas', stock: 5},
    {sku:'2', name:'Vestido azul claro', price: 45, image: './images/dress.png', description: 'Vestido azul claro para mujer con un corte a la moda y en algodon', category: 'Vestidos', stock: 3},
    {sku:'3', name:'Short blanco para mujer', price: 20, image: './images/wshort.png', description: 'Short blanco para mujer, corto y en mezclilla', category: 'Shorts', stock: 10},
    {sku:'4', name:'Falda a cuadros', price: 25, image: './images/skirt.png', description: 'Falda de mujer a cuadros rojos y negros, tela pesada', category: 'Faldas', stock: 8},
    {sku:'5', name:'Jean para hombre', price: 45, image: './images/jean.png', description: 'Jean oscuro para hombre', category: 'Jeans', stock: 5},
    {sku:'6', name:'Saco negro con capucha', price: 60, image: './images/hoodieb.png', description: 'Saco negro con capucha de tela abrigada', category: 'Sacos', stock: 6},
    {sku:'7', name:'Gorra negra', price: 15, image: './images/blackCap.png', description: 'Gorra negra sin horma', category: 'Gorras', stock: 12},
    {sku:'8', name:'Saco negro sin capucha', price: 40, image: './images/blackCrew.png', description: 'Saco negro sin capucha de tela abrigada', category: 'Sacos', stock: 7},
    {sku:'9', name:'Vestido negro perlado', price: 80, image: './images/blackDress.png', description: 'Vestido negro elegante con perlas brillantes', category: 'Vestidos', stock: 21},
    {sku:'10', name:'Falda negra', price: 20, image: './images/blackSkirt.png', description: 'Falda negra con botones', category: 'Faldas', stock: 15},
    {sku:'11', name:'Vestido azul rey', price: 40, image: './images/blueDress.png', description: 'Vestido azul rey elegante', category: 'Vestidos', stock: 18},
    {sku:'12', name:'Camisa azul', price: 40, image: './images/blueshirt.png', description: 'Camisa de botones azul claro elegante', category: 'Camisas', stock: 2},
    {sku:'13', name:'Camiseta deportiva', price: 60, image: './images/colombiaShirt.png', description: 'Camiseta deportiva del equipo colombiano de futbol', category: 'Camisetas', stock: 19},
    {sku:'14', name:'Short de mezclilla', price: 25, image: './images/denimShort.png', description: 'Short corto de mezclilla para mujer', category: 'Shorts', stock: 21},
    {sku:'15', name:'Camiseta gris', price: 20, image: './images/grayShirt.png', description: 'Camiseta basica gris para hombre', category: 'Camisetas', stock: 19},
    {sku:'16', name:'Short deportivo gris', price: 20, image: './images/grayShort.png', description: 'Short gris en tela deportiva', category: 'Shorts', stock: 6},
    {sku:'17', name:'Saco verde con capucha', price: 70, image: './images/greenHodie.png', description: 'Saco verde con capucha marca vans', category: 'Sacos', stock: 18},
    {sku:'18', name:'Camiseta verde', price: 25, image: './images/greenShirt.png', description: 'Camiseta verde para hombre', category: 'Camisetas', stock: 15},
    {sku:'19', name:'Jean azul claro', price: 80, image: './images/jeans2.png', description: 'Jean normal azul claro', category: 'Jeans', stock: 25},
    {sku:'20', name:'Blusa azul claro', price: 40, image: './images/lightBlueBlouse.png', description: 'Blusa azul claro de tela delgada', category: 'Blusas', stock: 21},
    {sku:'21', name:'Saco azul claro con capucha', price: 80, image: './images/lightBlueHoodie.png', description: 'Saco azul claro con capucha de tela abrigada', category: 'Sacos', stock: 3},
    {sku:'22', name:'Camiseta verde militar', price: 20, image: './images/MGreenShirt.png', description: 'Camiseta basica verde militar para hombre', category: 'Camisetas', stock: 4},
    {sku:'23', name:'Blusa naranja', price: 15, image: './images/orangeBlouse.png', description: 'Blusa naranja de tela pesada', category: 'Blusas', stock: 6},
    {sku:'24', name:'Blusa rosada', price: 20, image: './images/pinkBlouse.png', description: 'Blusa rosada sin mangas', category: 'Blusas', stock: 7},
    {sku:'25', name:'Short rosado', price: 30, image: './images/pinkShort.png', description: 'Short corto rosado para mujer', category: 'Shorts', stock: 12},
    {sku:'26', name:'Saco rojo con capucha', price: 75, image: './images/redHoodie.png', description: 'Saco rojo con capucha de tela abrigada', category: 'Sacos', stock: 16},
    {sku:'27', name:'Short rojo', price: 10, image: './images/redShort.png', description: 'Short corto rojo para mujer', category: 'Shorts', stock: 13},
    {sku:'28', name:'Saco blanco con capucha', price: 70, image: './images/whiteHoodie.png', description: 'Saco blanco con capucha de tela abrigada', category: 'Sacos', stock: 9},
    {sku:'29', name:'Jean ancho oscuro', price: 100, image: './images/wideJeans.png', description: 'Jean de corte ancho oscuro', category: 'Jeans', stock: 6},
    {sku:'30', name:'Jean ancho claro', price: 110, image: './images/wideJeans2.png', description: 'Jean de corte ancho claro', category: 'Jeans', stock: 3}
]

